### ISSUE TITLE
[Feature request] A way to use Knobster with other software

### ISSUE THREAD

**Issue by jbnl** [SimInnovations/libknobster#1]
Hi, I own several Knobsters and enjoy using them with Airmanager. I have them fixed to some screens. However, when I switch out my flight gear for racing gear, I have no way to use the Knobsters as input devices. I use Simhub to create and interact with dashboards, but this cannot handle Knobster. Nor do my racing games see Knobster as input when configuring controls. I wish there was a way to start a script or program to make Windows see the Knobster input so I could use them in either a tool like Simhub or directly as an input device in my racing sim games (such as + or - traction control, abs or even wiper speed). I know I can do this with arduino rotary encoders but then I have to remove my Knobsters from their fixed position to replace them with ugly diy rotaries. I’d much rather use the high quality Knobsters I already own. Unfortunately I cannot write C, so I was hoping someone could write a .bat or .exe file to run which registers the Knobster input as a valid button press to use in other tools than Airmanager.

**Comment by SimInnovations** [comment]
If it only was that easy :-) It would most probably have to act as a HID to use it in different software, or at least have it as generic as possible. But that would require different behavior from the Knobster itself, thus different firmware in the chip. Then comes the problem that it would have to be able to act as both, so how are you going to make it switch between Knobster and HID?
Of course you can come up with something like pressing the button for 3 seconds when powering on. But this wasn't the intention of our product...

**Comment by jbnl** [comment]
I think I understand the issue, that's too bad. Thanks for your quick response though :)

**Comment by SimInnovations** [comment]
If the racing game, or other software for that matter, has some sort of SDK/API, then one could interface with libknobster. But you would indeed have to have some programming skills.
